#ifndef LOGGER_H
#define LOGGER_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(Screen)
Q_DECLARE_LOGGING_CATEGORY(SmilParser)
Q_DECLARE_LOGGING_CATEGORY(ContentManager)
Q_DECLARE_LOGGING_CATEGORY(MediaPlayer)
Q_DECLARE_LOGGING_CATEGORY(MediaControl)
Q_DECLARE_LOGGING_CATEGORY(System)
Q_DECLARE_LOGGING_CATEGORY(TimeService)
Q_DECLARE_LOGGING_CATEGORY(PlayLog)

#endif // LOGGER_H
